# Generated by go2rpm 1.16.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}
%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/sagernet/gvisor
%global goihead gvisor
%global goipath github.com/sagernet/%{goihead}
Version:  20250319.0
%global tag             sagernet-20250319.0

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -L -f

%global common_description %{expand:
Application Kernel for Containers.}

%global golicenses      LICENSE
%global godocs          AUTHORS README.md

Name:           golang-github-sagernet-gvisor
Release:        %autorelease
Summary:        Application Kernel for Containers

License:        Apache-2.0
URL:            %{gourl}
Source: https://%{goipath}/archive/%{tag}/%{goihead}-%{tag}.tar.gz

%description %{common_description}

%gopkg

%prep
%goprep -A
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%go_generate_buildrequires
%endif

%install
%gopkginstall

%if %{without bootstrap}
%if %{with check}
%check

%endif
%endif

%gopkgfiles

%changelog
%autochangelog
